//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoG1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public long IdAuditoria { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Origen { get; set; }
        public Nullable<long> IdEstudiante { get; set; }
        public Nullable<long> IdInstitucion { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Institucion Institucion { get; set; }
    }
}
