//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoG1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conexion
    {
        public long IdConexion { get; set; }
        public long IdEstudianteSolicitante { get; set; }
        public long IdEstudianteReceptor { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Estado { get; set; }
        public string MensajeSolicitud { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Estudiante Estudiante1 { get; set; }
    }
}
