//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoG1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errores
    {
        public long Id { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Origen { get; set; }
        public Nullable<long> IdUsuario { get; set; }
    }
}
