//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoG1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public long IdNotificacion { get; set; }
        public long IdEstudiante { get; set; }
        public long IdInstitucion { get; set; }
        public long IdPostulacion { get; set; }
        public long IdProyecto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Contenido { get; set; }
        public bool TipoNotificacion { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Institucion Institucion { get; set; }
        public virtual Postulacion Postulacion { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
