//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoG1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public long IdNotificacion { get; set; }
        public long IdEstudiante { get; set; }
        public long IdInstitucion { get; set; }
        public long IdPostulacion { get; set; }
        public long IdProyecto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Contenido { get; set; }
        public bool TipoNotificacion { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Institucion Institucion { get; set; }
        public virtual Postulacion Postulacion { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
