//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoG1.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conexion
    {
        public long IdConexion { get; set; }
        public long IdEstudianteSolicitante { get; set; }
        public long IdEstudianteReceptor { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Estado { get; set; }
        public string MensajeSolicitud { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Estudiante Estudiante1 { get; set; }
    }
}
